version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: cimg/ruby:3.1-browsers

caches:
  - &bundle_cache_full v2-repo- {{ checksum "Gemfile.lock" }}
  - &bundle_cache v2-repo-

commands:
  defaults:
    steps:
      - checkout
      - restore_cache:
          keys:
            - *bundle_cache_full
            - *bundle_cache
      - run: bundle install --path vendor/bundle_cache
      - save_cache:
          key: *bundle_cache_full
          paths:
            - vendor/bundle_cache
  run_linters:
    description: command to start linters
    steps:
      - run:
          name: rubocop
          command: bundle exec rubocop
jobs:
  lintering:
    executor: default
    steps:
      - defaults
      - run_linters
      
workflows:
  build:
    jobs:
      - lintering
      