version: 2.1

executors:
  default:
    working_directory: ~/repo
    discription: The official CircleCI Ruby Docker image
    docker:
      - image: cimg/ruby:3.1-browsers

caches:
  - &bundle_cache_full v2-repo- {{ checksum "Gemfile.lock" }}
  - &bundle_cache c2-repo-

commands:
  defaults:
    steps:
      - checkout
      - restore_cache:
          keys:
            - *bundle_cache_full
            - *bundle_cache
      - run: bundle install --path vendor/bundle_cache
      - save_cache:
          key: *bundle_cache_full
          paths:
            - vendor/bundle_cache
jobs:
  lintering:
    executor: default
    steps:
      - defaults
      
workflows:
  build:
    jobs:
      - lintering